export type Message = { id: string; role: 'agent' | 'user'; text: string }
export type WorkspaceFile = { path: string; kind: 'tsx' | 'css' | 'ts' | 'md'; status: 'ready' | 'changed'; content?: string }
export type ActivityItem = { id: string; title: string; detail: string; state: 'done' | 'active' | 'waiting' }

export const starterFiles: WorkspaceFile[] = [
  { path: 'app/page.tsx', kind: 'tsx', status: 'ready', content: '// Nexora workspace entrypoint\n' },
  { path: 'app/globals.css', kind: 'css', status: 'ready', content: '/* Workspace styles */\n' },
  { path: 'lib/agent.ts', kind: 'ts', status: 'changed', content: 'export const agent = "Nexora"\n' },
  { path: 'README.md', kind: 'md', status: 'ready', content: '# Nexora workspace\n' },
]

export const starterActivity: ActivityItem[] = [
  { id: 'brief', title: 'Brief understood', detail: 'Workspace initialized', state: 'done' },
  { id: 'scaffold', title: 'Scaffolding files', detail: 'app/page.tsx', state: 'active' },
  { id: 'direction', title: 'Waiting for direction', detail: 'Your next message', state: 'waiting' },
]

export function exportWorkspace(files: WorkspaceFile[]) {
  return `NEXORA WORKSPACE\n\n${files.map((file) => `- ${file.path}`).join('\n')}\n\nGenerated by Nexora AI.`
}

export function downloadText(filename: string, content: string) {
  const blob = new Blob([content], { type: 'text/plain;charset=utf-8' })
  const url = URL.createObjectURL(blob)
  const anchor = document.createElement('a')
  anchor.href = url
  anchor.download = filename
  anchor.click()
  URL.revokeObjectURL(url)
}

export function makeId() {
  return `${Date.now()}-${Math.random().toString(36).slice(2)}`
}

export const initialMessage: Message = {
  id: 'welcome',
  role: 'agent',
  text: 'I’m ready. Tell me what you want to build and I’ll turn the brief into a working system.',
}

export type WorkspaceState = {
  messages: Message[]
  files: WorkspaceFile[]
  activity: ActivityItem[]
}

export function createWorkspace(): WorkspaceState {
  return { messages: [initialMessage], files: starterFiles, activity: starterActivity }
}

export function parseWorkspace(value: string): WorkspaceState | null {
  try {
    const parsed = JSON.parse(value) as WorkspaceState
    if (!Array.isArray(parsed.messages) || !Array.isArray(parsed.files)) return null
    return parsed
  } catch {
    return null
  }
}

export function workspaceStorageKey() {
  return 'nexora-workspace-v1'
}
