import { kindFromPath, STACKS, type StackId } from '@/lib/stacks'

export type Message = { id: string; role: 'agent' | 'user'; text: string }
export type WorkspaceFile = {
  path: string
  kind: string
  status: 'ready' | 'changed'
  content?: string
}
export type ActivityItem = {
  id: string
  title: string
  detail: string
  state: 'done' | 'active' | 'waiting'
}

export const starterFiles: WorkspaceFile[] = Object.entries(STACKS.find((s) => s.id === 'nextjs')!.seed).map(
  ([path, content]) => ({
    path,
    kind: kindFromPath(path),
    status: 'ready' as const,
    content,
  }),
)

export const starterActivity: ActivityItem[] = [
  { id: 'brief', title: 'Brief understood', detail: 'Workspace initialized', state: 'done' },
  { id: 'scaffold', title: 'Scaffolding files', detail: 'Multi-stack ready', state: 'active' },
  { id: 'direction', title: 'Waiting for direction', detail: 'Your next message', state: 'waiting' },
]

export function filesForStack(stackId: StackId): WorkspaceFile[] {
  const stack = STACKS.find((s) => s.id === stackId)
  if (!stack) return starterFiles
  return Object.entries(stack.seed).map(([path, content]) => ({
    path,
    kind: kindFromPath(path),
    status: 'ready' as const,
    content,
  }))
}

export function exportWorkspace(files: WorkspaceFile[]) {
  const body = files
    .map((file) => `----- ${file.path} -----\n${file.content ?? ''}`)
    .join('\n\n')
  return `NEXORA WORKSPACE\n\nFiles:\n${files.map((f) => `- ${f.path}`).join('\n')}\n\n${body}\n\nGenerated by Nexora AI.\n`
}

export function downloadText(filename: string, content: string) {
  const blob = new Blob([content], { type: 'text/plain;charset=utf-8' })
  const url = URL.createObjectURL(blob)
  const anchor = document.createElement('a')
  anchor.href = url
  anchor.download = filename
  anchor.click()
  URL.revokeObjectURL(url)
}

export function makeId() {
  return `${Date.now()}-${Math.random().toString(36).slice(2)}`
}

export const initialMessage: Message = {
  id: 'welcome',
  role: 'agent',
  text: 'I\u2019m ready. I can build in TypeScript, Python, React, Next.js, Vite, and Vue. Tell me what you want and which stack to use.',
}

export type WorkspaceState = {
  messages: Message[]
  files: WorkspaceFile[]
  activity: ActivityItem[]
}

export function createWorkspace(): WorkspaceState {
  return { messages: [initialMessage], files: starterFiles, activity: starterActivity }
}

export function parseWorkspace(value: string): WorkspaceState | null {
  try {
    const parsed = JSON.parse(value) as WorkspaceState
    if (!Array.isArray(parsed.messages) || !Array.isArray(parsed.files)) return null
    return parsed
  } catch {
    return null
  }
}

export function workspaceStorageKey() {
  return 'nexora-workspace-v2'
}
