import { kindFromPath, STACKS, type StackId } from '@/lib/stacks'

export type Message = { id: string; role: 'agent' | 'user'; text: string; runId?: string }
export type WorkspaceFile = { path: string; kind: string; status: 'ready' | 'changed'; content?: string }
export type ActivityItem = { id: string; title: string; detail: string; state: 'done' | 'active' | 'waiting' }
export type ValidationResult = { status: 'passed' | 'failed' | 'skipped' | 'running'; summary: string; logs?: string; runId?: string }
export type RunRecord = { id: string; prompt: string; startedAt: string; finishedAt?: string; status: 'running' | 'completed' | 'failed'; changedFiles: string[]; validation?: ValidationResult }

export type WorkspaceState = {
  version: 3
  project: { name: string; mode: string; selectedFile: string | null }
  messages: Message[]
  files: WorkspaceFile[]
  activity: ActivityItem[]
  runs: RunRecord[]
  validation: ValidationResult | null
}

export const LIMITS = { prompt: 8000, files: 120, fileBytes: 120000, workspaceBytes: 900000 }
export const starterFiles: WorkspaceFile[] = Object.entries(STACKS.find((s) => s.id === 'nextjs')!.seed).map(([path, content]) => ({ path, kind: kindFromPath(path), status: 'ready', content }))
export const starterActivity: ActivityItem[] = [
  { id: 'brief', title: 'Brief understood', detail: 'Workspace initialized', state: 'done' },
  { id: 'scaffold', title: 'Scaffolding files', detail: 'Multi-stack ready', state: 'done' },
  { id: 'direction', title: 'Waiting for direction', detail: 'Your next message', state: 'waiting' },
]
export const initialMessage: Message = { id: 'welcome', role: 'agent', text: 'I’m ready. I can inspect, build, validate, and package a project in TypeScript, Python, React, Next.js, Vite, or Vue.' }

export function filesForStack(stackId: StackId): WorkspaceFile[] {
  const stack = STACKS.find((s) => s.id === stackId)
  return stack ? Object.entries(stack.seed).map(([path, content]) => ({ path, kind: kindFromPath(path), status: 'ready', content })) : starterFiles
}
export function createWorkspace(): WorkspaceState { return { version: 3, project: { name: 'Untitled build', mode: 'Next.js', selectedFile: starterFiles[0]?.path ?? null }, messages: [initialMessage], files: starterFiles, activity: starterActivity, runs: [], validation: null } }
export function isSafePath(path: string) { return Boolean(path) && path.length <= 240 && !path.startsWith('/') && !path.includes('..') && !path.includes('\\') }
export function validateFiles(files: Record<string, string>) { const entries = Object.entries(files); if (entries.length > LIMITS.files) throw new Error(`Workspace exceeds ${LIMITS.files} files.`); let bytes = 0; for (const [path, content] of entries) { if (!isSafePath(path)) throw new Error(`Unsafe file path: ${path}`); if (content.length > LIMITS.fileBytes) throw new Error(`File exceeds ${LIMITS.fileBytes} bytes: ${path}`); bytes += content.length } if (bytes > LIMITS.workspaceBytes) throw new Error('Workspace exceeds the total size limit.'); return files }
export function exportWorkspace(files: WorkspaceFile[]) { return `NEXORA WORKSPACE\n\nFiles:\n${files.map((f) => `- ${f.path}`).join('\n')}\n\n${files.map((f) => `----- ${f.path} -----\n${f.content ?? ''}`).join('\n\n')}\n\nGenerated by Nexora AI.\n` }
export function downloadText(filename: string, content: string) { const blob = new Blob([content], { type: 'text/plain;charset=utf-8' }); const url = URL.createObjectURL(blob); const anchor = document.createElement('a'); anchor.href = url; anchor.download = filename; anchor.click(); URL.revokeObjectURL(url) }
export function makeId() { return `${Date.now()}-${Math.random().toString(36).slice(2)}` }
export function parseWorkspace(value: string): WorkspaceState | null { try { const raw = JSON.parse(value) as Partial<WorkspaceState>; if (!Array.isArray(raw.messages) || !Array.isArray(raw.files)) return null; const base = createWorkspace(); return { ...base, ...raw, version: 3, project: { ...base.project, ...(raw.project ?? {}) }, activity: Array.isArray(raw.activity) ? raw.activity : base.activity, runs: Array.isArray(raw.runs) ? raw.runs : [], validation: raw.validation ?? null } as WorkspaceState } catch { return null } }
export function workspaceStorageKey() { return 'nexora-workspace-v3' }
